// ============================================================
// SLA STUDY HUB — data.js
// All vocabulary terms extracted from fc_ch02–ch10.pptx
// Organized by chapter with related-concept links
// ============================================================
 
const CHAPTERS = [
  { id: "ch2",  label: "Ch 2", title: "FLA Foundations",        color: "#74b9ff" },
  { id: "ch3",  label: "Ch 3", title: "Bilingualism",           color: "#fd79a8" },
  { id: "ch4",  label: "Ch 4", title: "SLA Theories",           color: "#ffd166" },
  { id: "ch5",  label: "Ch 5", title: "Cognitive Approaches",   color: "#06d6a0" },
  { id: "ch6",  label: "Ch 6", title: "Teaching Methods",       color: "#ff6b6b" },
  { id: "ch7",  label: "Ch 7", title: "L2 Development",         color: "#a29bfe" },
  { id: "ch8",  label: "Ch 8", title: "Age & CPH",              color: "#fdcb6e" },
  { id: "ch9",  label: "Ch 9", title: "Individual Differences", color: "#55efc4" },
  { id: "ch10", label: "Ch10", title: "Bilingual Cognition",    color: "#e17055" },
];
 
const TERMS = [
  // ─── CHAPTER 2 ───────────────────────────────────────────
  { id:"t001", chapter:"ch2", term:"behaviorism", abbr:"",
    def:"Theoretical view proposing that learning principles can explain most behavior, and that observable events—rather than mental activity—are the proper objects of study.",
    example:"Skinner argued that children learn language through reinforcement of correct utterances.",
    related:["t004","t021"] },
  { id:"t002", chapter:"ch2", term:"child-directed speech", abbr:"CDS",
    def:"A special speech register used by adults and older children when speaking to younger children and infants, characterized by exaggerated intonation and considerable repetition.",
    example:"'Look at the DOGGY! Is that a doggy? Yes, that's a DOGGY!' is classic CDS.",
    related:["t003","t008"] },
  { id:"t003", chapter:"ch2", term:"CHILDES", abbr:"Child Language Data Exchange System",
    def:"An online corpus that has grown to include numerous transcripts of dialogues between children and adults and older children, used for analyzing language development.",
    example:"Researchers use CHILDES transcripts to measure MLU growth across age groups.",
    related:["t002","t012"] },
  { id:"t004", chapter:"ch2", term:"connectionism", abbr:"",
    def:"Theoretical view proposing that language is learned through exposure to input allowing the construction of associations among units—sound sequences, words, sentence patterns, etc.",
    example:"A connectionist model learns that '-ed' often signals past tense by seeing thousands of examples.",
    related:["t001","t006"] },
  { id:"t005", chapter:"ch2", term:"emergentism", abbr:"",
    def:"Theoretical view that phenomena of language are best explained by reference to more basic non-linguistic factors and their interaction—physiology, perception, processing, and input properties.",
    example:"Emergentists argue that the passive construction emerges from general cognitive biases, not an innate grammar.",
    related:["t004","t006"] },
  { id:"t006", chapter:"ch2", term:"empiricism", abbr:"",
    def:"Theoretical view that emphasizes the role of the environment and experience over that of innate ideas or capacities.",
    example:"An empiricist account of L1 acquisition stresses the quantity and quality of input the child receives.",
    related:["t015","t001"] },
  { id:"t007", chapter:"ch2", term:"formulaic sequences", abbr:"",
    def:"Phrases that learners learn and use as a whole unit, without analyzing them into individual components (e.g., 'How are you?' used as a single chunk).",
    example:"Early L2 learners often produce 'I don't know' as a chunk before they understand 'don't'.",
    related:["t008","t009"] },
  { id:"t008", chapter:"ch2", term:"high amplitude sucking", abbr:"HAS",
    def:"A technique used to study infant perceptual abilities; typically involves recording an infant's sucking rate as a measure of its attention to various stimuli.",
    example:"Infants suck faster on a pacifier when they hear a novel sound, showing phoneme discrimination.",
    related:["t002"] },
  { id:"t009", chapter:"ch2", term:"input", abbr:"",
    def:"The language to which an individual is exposed in the environment.",
    example:"A child raised in a bilingual home receives input in two languages simultaneously.",
    related:["t002","t007","t041"] },
  { id:"t010", chapter:"ch2", term:"interactionism", abbr:"",
    def:"Theoretical viewpoint that recognizes the role of experience and the environment as well as the contribution of innate capacities in language acquisition.",
    example:"A child's language grows through both innate grammar capacity AND interaction with caregivers.",
    related:["t015","t006"] },
  { id:"t011", chapter:"ch2", term:"interference", abbr:"",
    def:"The influence of L1 on L2 when it leads to an error, or vice versa.",
    example:"A French speaker saying 'I am here since three years' (calque of French structure) shows interference.",
    related:["t034","t033"] },
  { id:"t012", chapter:"ch2", term:"metalinguistic awareness", abbr:"",
    def:"Ability to reflect on language as an object—to think about how language works rather than just using it.",
    example:"Knowing that 'cats' has two morphemes (-cat- and -s) requires metalinguistic awareness.",
    related:["t013","t003"] },
  { id:"t013", chapter:"ch2", term:"mean length of utterance", abbr:"MLU",
    def:"Measurement used to calculate the development of children's grammar: number of morphemes divided by total number of utterances.",
    example:"'Dog gone' = 2 morphemes / 1 utterance → MLU of 2. Increases reliably with language development.",
    related:["t014","t012"] },
  { id:"t014", chapter:"ch2", term:"morpheme", abbr:"",
    def:"Smallest meaning-bearing unit of language (e.g., free morphemes like 'dog', and bound morphemes like the plural '-s').",
    example:"'Dogs' contains two morphemes: {dog} + {-s}. 'Unfriendly' contains three: {un-} + {friend} + {-ly}.",
    related:["t013"] },
  { id:"t015", chapter:"ch2", term:"nativism", abbr:"",
    def:"A theoretical approach emphasizing the innate, possibly genetic, contributions to language acquisition—associated with Chomsky's Universal Grammar.",
    example:"The fact that all children acquire complex grammar without explicit instruction supports nativist claims.",
    related:["t006","t010","t039"] },
  { id:"t016", chapter:"ch2", term:"nonreduplicated babbling", abbr:"variegated babbling",
    def:"Babbling in which young children vary the consonant-vowel sequences used; for example, 'ba-da-ga.'",
    example:"At 9–10 months, infants begin producing varied sequences like 'ba-di-ga' rather than 'ba-ba-ba'.",
    related:["t017"] },
  { id:"t017", chapter:"ch2", term:"reduplicated babbling", abbr:"",
    def:"Babbling in which consonant-vowel combinations are repeated, such as 'ba-ba-ba' or 'ma-ma-ma.'",
    example:"At around 6–8 months, infants begin producing rhythmic repeated syllables.",
    related:["t016"] },
  { id:"t018", chapter:"ch2", term:"object permanence", abbr:"",
    def:"The understanding an infant gains during the latter part of the first year that objects continue to exist even when they are no longer visible.",
    example:"A child who searches for a toy hidden under a blanket has developed object permanence.",
    related:[] },
  { id:"t019", chapter:"ch2", term:"overextension", abbr:"",
    def:"A child's use of a word for objects or items that share a feature or property with the prototype; e.g., using 'dog' to refer to all four-legged animals.",
    example:"A toddler who calls every man 'daddy' is overextending the word.",
    related:["t020"] },
  { id:"t020", chapter:"ch2", term:"overgeneralization", abbr:"",
    def:"The use of a grammatical rule in contexts where it is not appropriate, e.g., 'I goed' or 'I hurted my arm'—applying the regular past-tense rule to irregular verbs.",
    example:"'She runned fast' = overgeneralization of the '-ed' past tense rule.",
    related:["t019","t033"] },
  { id:"t021", chapter:"ch2", term:"underextension", abbr:"",
    def:"A child's use of a word with a narrower meaning than in the adult language; e.g., 'dog' to refer only to the family pet, not all dogs.",
    example:"A child who only uses 'cup' for their own special sippy cup is underextending.",
    related:["t019"] },
 
  // ─── CHAPTER 3 ───────────────────────────────────────────
  { id:"t022", chapter:"ch3", term:"additive bilingualism", abbr:"",
    def:"A language learning situation in which learning a second language is not at the expense of the L1; both languages are supported and valued by the community.",
    example:"French immersion students in Canada typically show additive bilingualism—English is maintained alongside French.",
    related:["t023","t026"] },
  { id:"t023", chapter:"ch3", term:"subtractive bilingualism", abbr:"",
    def:"A language learning situation in which the majority language is learned at the expense of the native language of minority-language speakers.",
    example:"Immigrant children who lose their heritage language as they acquire English experience subtractive bilingualism.",
    related:["t022","t025"] },
  { id:"t024", chapter:"ch3", term:"bilingual education", abbr:"",
    def:"Schooling in two languages; in the US specifically refers to programs designed for minority-language children using both L1 and the majority language as mediums of instruction.",
    example:"A Spanish-English bilingual program teaches math in Spanish on Monday and English on Tuesday.",
    related:["t025","t026"] },
  { id:"t025", chapter:"ch3", term:"heritage language", abbr:"",
    def:"A language acquired by individuals raised in homes where the dominant language in the larger society is not spoken or not exclusively spoken.",
    example:"A third-generation Korean-American who grew up hearing Korean at home has Korean as a heritage language.",
    related:["t023","t024"] },
  { id:"t026", chapter:"ch3", term:"immersion education", abbr:"",
    def:"A form of bilingual education in which students are taught through the medium of a second language, along with some instruction through their L1.",
    example:"Canadian French immersion schools teach subjects like math and science entirely in French.",
    related:["t022","t024"] },
  { id:"t027", chapter:"ch3", term:"dual-language instruction", abbr:"",
    def:"Language education in which children who are native speakers from each of the target language communities—both majority and minority language speakers—share the classroom.",
    example:"A 50-50 English-Spanish dual-language class includes both English-dominant and Spanish-dominant students.",
    related:["t024","t022"] },
  { id:"t028", chapter:"ch3", term:"translanguaging", abbr:"",
    def:"The purposeful pedagogical alternation of language mode of input and output in bilingual classrooms, validating all languages known by learners as cognitive resources.",
    example:"A teacher allows students to brainstorm in Spanish, draft in English, and share in either language.",
    related:["t027","t085"] },
 
  // ─── CHAPTER 4 ───────────────────────────────────────────
  { id:"t029", chapter:"ch4", term:"Monitor Model", abbr:"",
    def:"Krashen's model of SLA based on the concept that learners have two systems—acquisition and learning—and that the learned system acts as a monitor (editor) on the acquired system.",
    example:"An advanced learner mentally checks 'Is this grammatical?' before writing formal email—using the monitor.",
    related:["t030","t031","t032","t033","t040"] },
  { id:"t030", chapter:"ch4", term:"Acquisition-Learning Hypothesis", abbr:"",
    def:"Krashen's proposal that only 'acquired' (subconscious) knowledge leads to productive output; 'learned' conscious knowledge of rules only serves as a monitor/editor.",
    example:"A fluent speaker who 'just knows' a sentence sounds wrong is using acquired knowledge.",
    related:["t029","t057"] },
  { id:"t031", chapter:"ch4", term:"Affective Filter Hypothesis", abbr:"",
    def:"Krashen's hypothesis that an affective filter (anxiety, low motivation, low self-confidence) can block access to language acquisition even when comprehensible input is available.",
    example:"A student who is terrified of making errors in class may have a high affective filter blocking acquisition.",
    related:["t029","t096"] },
  { id:"t032", chapter:"ch4", term:"Comprehensible Input Hypothesis", abbr:"i+1",
    def:"Krashen's hypothesis that the most effective way to increase L2 competence is exposure to input that is one level beyond the learner's current level (i+1).",
    example:"A beginning learner benefits most from simple stories, not academic journals.",
    related:["t029","t051","t009"] },
  { id:"t033", chapter:"ch4", term:"Natural Order Hypothesis", abbr:"",
    def:"Krashen's hypothesis that grammatical structures of L2 are acquired in a predictable order, similar to L1 acquisition order, regardless of the order taught.",
    example:"English learners acquire progressive '-ing' before third-person '-s' regardless of instruction sequence.",
    related:["t029","t020"] },
  { id:"t034", chapter:"ch4", term:"contrastive analysis", abbr:"CA",
    def:"The comparison of the linguistic structures of two or more languages to determine their similarities and differences; used in the 1950s–60s to predict L2 difficulty.",
    example:"Contrastive analysis predicted Spanish speakers would struggle with English articles (Spanish lacks them).",
    related:["t035","t011","t036"] },
  { id:"t035", chapter:"ch4", term:"Contrastive Analysis Hypothesis", abbr:"CAH",
    def:"The strong-form hypothesis predicting that where there are similarities between L1 and L2, learning will be easy; where there are differences, there will be difficulty.",
    example:"CAH predicts Italian speakers will find Spanish easier than Chinese speakers would.",
    related:["t034","t036"] },
  { id:"t036", chapter:"ch4", term:"cross-linguistic influence", abbr:"CLI",
    def:"Refers to instances of phonological, lexical, grammatical, or other aspects of transfer from one language to another—positive transfer (facilitation) or negative transfer (interference).",
    example:"A German speaker using Subject-Verb-Object word order in English shows positive CLI.",
    related:["t034","t035","t011"] },
  { id:"t037", chapter:"ch4", term:"developmental error", abbr:"",
    def:"An error in learner language that does not result from L1 transfer but reflects the learner's gradual hypothesis-testing of the L2 system.",
    example:"'I goed' made by speakers of any L1 is a developmental error—it mirrors children's L1 overgeneralization.",
    related:["t038","t020","t033"] },
  { id:"t038", chapter:"ch4", term:"Error Analysis", abbr:"EA",
    def:"An approach to L2 research involving the description and classification of learner errors to gain insight into the learner's current underlying knowledge of the L2.",
    example:"EA revealed that many learner errors were developmental, not due to L1 interference—challenging the CAH.",
    related:["t037","t039"] },
  { id:"t039", chapter:"ch4", term:"interlanguage", abbr:"IL",
    def:"Selinker's (1972) term for the language system produced by an L2 learner that is distinct from both the L1 and the target L2—systematic, variable, and dynamic.",
    example:"A learner's grammar that treats 'he go' as correct is part of their interlanguage at that stage.",
    related:["t038","t037","t072"] },
  { id:"t040", chapter:"ch4", term:"Universal Grammar", abbr:"UG",
    def:"Chomsky's theory of the innate principles and properties that characterize the grammars of all human languages; the theoretical view associated with language as a distinct mental faculty.",
    example:"The fact that all languages have noun phrases and verb phrases is cited as evidence for UG.",
    related:["t015","t041","t029"] },
  { id:"t041", chapter:"ch4", term:"parameters", abbr:"",
    def:"In UG, small sets of alternatives for a given grammatical feature across languages—e.g., whether the head of a phrase precedes or follows its complement (head-first vs. head-last).",
    example:"English is head-first (verb before object); Japanese is head-last (object before verb).",
    related:["t040"] },
  { id:"t042", chapter:"ch4", term:"sociocultural theory", abbr:"SCT",
    def:"Applied to SLA (from Vygotsky), the view that social interaction is necessary for L2 development and that learning must be examined in its social context.",
    example:"Learning grammar by discussing it with a tutor (social interaction) is more effective than studying alone.",
    related:["t043","t044"] },
  { id:"t043", chapter:"ch4", term:"scaffolding", abbr:"",
    def:"In sociocultural theory, the support provided by teachers, peers, or more capable others to help a learner accomplish something they could not do independently.",
    example:"A teacher who asks guiding questions—'Is it past or present?'—to help a student self-correct is scaffolding.",
    related:["t042","t044"] },
  { id:"t044", chapter:"ch4", term:"zone of proximal development", abbr:"ZPD",
    def:"Vygotsky's concept: the distance between what a learner can do independently and what they can do with assistance from a more capable peer or teacher.",
    example:"If a student can write simple sentences alone but paragraphs with help, the gap is their ZPD.",
    related:["t042","t043"] },
 
  // ─── CHAPTER 5 ───────────────────────────────────────────
  { id:"t045", chapter:"ch5", term:"automatic processing", abbr:"",
    def:"In an information-processing view, the fast, effortless cognitive processing that characterizes highly practiced skills, with few demands on working memory.",
    example:"A fluent reader recognizes words automatically; a beginning reader consciously decodes each letter.",
    related:["t046","t054"] },
  { id:"t046", chapter:"ch5", term:"controlled processing", abbr:"",
    def:"In an information-processing view, the slow, effortful cognitive processing that characterizes new skill learning, limited by working memory capacity.",
    example:"Mentally checking subject-verb agreement while writing is controlled processing.",
    related:["t045","t054"] },
  { id:"t047", chapter:"ch5", term:"cognitive linguistics", abbr:"CL",
    def:"An approach that views meaning as central to language and sees language as inextricably linked to cognition and embodied experience—rejecting a separate language module.",
    example:"CL explains why 'the future is ahead of us' makes sense in terms of our physical experience moving through space.",
    related:["t048"] },
  { id:"t048", chapter:"ch5", term:"complex adaptive system", abbr:"CAS",
    def:"The view that language is a dynamic system that is acquired and develops through the combined influences of social interaction and cognitive processes, without a fixed endpoint.",
    example:"L2 proficiency emerges from countless social interactions and cognitive adaptations, not from a preset acquisition device.",
    related:["t047","t005"] },
  { id:"t049", chapter:"ch5", term:"Comprehensible Output Hypothesis", abbr:"",
    def:"Swain's (1985) proposal that having to produce L2 output—speaking and writing—forces learners to notice gaps in their knowledge and thereby leads to improved proficiency.",
    example:"When a student attempts to explain a concept in L2 and can't, they notice what grammar they need.",
    related:["t032","t050","t053"] },
  { id:"t050", chapter:"ch5", term:"Interaction Hypothesis", abbr:"",
    def:"Long's (1983) proposal that interactional modification—negotiating meaning when communication breaks down—makes input comprehensible and thereby promotes acquisition.",
    example:"When a teacher repeats back a clarification request and the learner reformulates, acquisition is occurring.",
    related:["t049","t051","t052"] },
  { id:"t051", chapter:"ch5", term:"input processing", abbr:"IP",
    def:"VanPatten's model of how learners make form-meaning connections: because processing capacity is limited, learners prioritize meaning over grammatical form.",
    example:"Learners understand 'Yesterday I go to school' as past tense because of 'yesterday'—ignoring the missing '-ed'.",
    related:["t009","t032","t065"] },
  { id:"t052", chapter:"ch5", term:"negotiation for meaning", abbr:"",
    def:"The interactional process in which learners and interlocutors adjust their speech—using clarification requests, comprehension checks, and recasts—until mutual understanding is achieved.",
    example:"'Pardon?' or 'What do you mean by X?' initiates negotiation for meaning.",
    related:["t050","t053"] },
  { id:"t053", chapter:"ch5", term:"negative feedback", abbr:"",
    def:"Any signal that draws the learner's attention to an incorrect or non-target-like L2 utterance—including explicit correction, recasts, and metalinguistic cues.",
    example:"Recasting 'He go to school' as 'Yes, he goes to school, right' is implicit negative feedback.",
    related:["t054","t052","t063"] },
  { id:"t054", chapter:"ch5", term:"Noticing Hypothesis", abbr:"",
    def:"Schmidt's (1995) hypothesis that what learners consciously notice in the input is what becomes intake for learning; unnoticed input does not drive acquisition.",
    example:"Underlining grammar targets in a reading text increases noticing and therefore learning.",
    related:["t045","t056","t009"] },
  { id:"t055", chapter:"ch5", term:"declarative knowledge", abbr:"",
    def:"Knowledge that something is the case—'knowing that'—such as knowing a grammar rule explicitly.",
    example:"Knowing 'In English, the third-person singular present requires -s' is declarative knowledge.",
    related:["t056","t045"] },
  { id:"t056", chapter:"ch5", term:"procedural knowledge", abbr:"",
    def:"Knowledge of how to do something—'knowing how'—which underlies fluent, automatic performance.",
    example:"Being able to produce correct third-person -s effortlessly in speech is procedural knowledge.",
    related:["t055","t045"] },
  { id:"t057", chapter:"ch5", term:"explicit knowledge", abbr:"",
    def:"Conscious, verbalizable knowledge about the L2—grammar rules, vocabulary definitions—that the learner can articulate.",
    example:"Being able to state 'adjectives precede nouns in English' is explicit knowledge.",
    related:["t058","t055","t030"] },
  { id:"t058", chapter:"ch5", term:"implicit knowledge", abbr:"",
    def:"Knowledge of L2 that underlies the learner's performance but is not consciously accessible—the intuitive sense of correctness.",
    example:"A native speaker who 'just knows' a sentence sounds wrong has implicit knowledge.",
    related:["t057","t056"] },
  { id:"t059", chapter:"ch5", term:"intake", abbr:"",
    def:"The portion of the input that the learner actually notices and processes for acquisition; input that is comprehended but not noticed does not become intake.",
    example:"A learner reading a text may comprehend the meaning but not notice (take in) the passive voice constructions.",
    related:["t009","t054"] },
  { id:"t060", chapter:"ch5", term:"noticing", abbr:"",
    def:"The process of paying conscious attention to a feature of the input—a prerequisite for that feature to become intake, according to Schmidt.",
    example:"Typographically bolding the target structure in a text enhances noticing.",
    related:["t054","t059"] },
  { id:"t061", chapter:"ch5", term:"output", abbr:"",
    def:"The language that the learner produces—in speaking or writing.",
    example:"Encouraging learners to produce more output creates more opportunities to notice gaps.",
    related:["t049","t009"] },
  { id:"t062", chapter:"ch5", term:"recasts", abbr:"",
    def:"A teacher's or interlocutor's reformulation of a learner's incorrect utterance in correct target-like form, without explicitly signaling that it was an error.",
    example:"Student: 'She runned fast.' Teacher: 'Oh, she ran fast? Interesting!' ← this is a recast.",
    related:["t053","t063"] },
  { id:"t063", chapter:"ch5", term:"skill acquisition theory", abbr:"",
    def:"The view applied to SLA that language learning proceeds from explicit declarative knowledge to implicit procedural knowledge through practice—the same as learning any cognitive skill.",
    example:"First you consciously know the grammar rule, then through practice it becomes automatic.",
    related:["t055","t056","t045"] },
  { id:"t064", chapter:"ch5", term:"perceptual salience", abbr:"",
    def:"The degree to which a linguistic feature stands out in the input—stressed, frequent, and form-meaning transparent features are more salient and easier to acquire.",
    example:"Word-final consonants are less perceptually salient than stressed vowels, so learners drop them.",
    related:["t054","t060"] },
  { id:"t065", chapter:"ch5", term:"information-processing approach", abbr:"",
    def:"A cognitive approach to SLA, stemming from cognitive psychology, that emphasizes the mental processes—attention, memory, practice—involved in L2 acquisition and use.",
    example:"The IP approach studies how learners allocate limited attention between fluency and accuracy.",
    related:["t045","t046","t051"] },
 
  // ─── CHAPTER 6 ───────────────────────────────────────────
  { id:"t066", chapter:"ch6", term:"Audiolingual Method", abbr:"ALM",
    def:"A language teaching method, rooted in behaviorism and structural linguistics, that develops language habits through repetitive oral drills and pattern practice.",
    example:"'Repeat after me: I GO to school. She GOES to school. He GOES to school.' — ALM drill.",
    related:["t001","t067","t068"] },
  { id:"t067", chapter:"ch6", term:"Communicative Language Teaching", abbr:"CLT",
    def:"An approach emphasizing the use of techniques that engage learners in authentic, meaningful communicative activities, prioritizing the pragmatic function of language.",
    example:"Role-playing a job interview in class is a CLT activity.",
    related:["t066","t075","t076"] },
  { id:"t068", chapter:"ch6", term:"Grammar Translation Method", abbr:"GTM",
    def:"A classical teaching method emphasizing explicit grammar instruction, reading literary texts, and translating sentences between L1 and L2.",
    example:"Students memorize Latin verb conjugation tables and translate Caesar's writings in GTM classes.",
    related:["t069","t066"] },
  { id:"t069", chapter:"ch6", term:"Direct Method", abbr:"",
    def:"An approach developed in reaction to the GTM that gave priority to oral expression and avoided recourse to the learner's native language in instruction.",
    example:"The Berlitz Method is a famous application—instruction is entirely in the target language.",
    related:["t068","t066"] },
  { id:"t070", chapter:"ch6", term:"Total Physical Response", abbr:"TPR",
    def:"Asher's method allowing learners to develop comprehension before speaking by responding physically to commands in the target language.",
    example:"'Stand up! Touch your nose! Walk to the door!'—learners act without speaking.",
    related:["t071","t067"] },
  { id:"t071", chapter:"ch6", term:"Suggestopedia", abbr:"",
    def:"Georgi Lozanov's L2 teaching approach that promotes a relaxed, stress-free environment—using music, art, and comfortable seating—to remove affective barriers to learning.",
    example:"Baroque music played during vocabulary presentation is used to induce a receptive mental state.",
    related:["t031","t070"] },
  { id:"t072", chapter:"ch6", term:"focus on form", abbr:"FFI (form-focused instruction)",
    def:"Drawing students' attention to aspects of linguistic form within classrooms characterized by a meaning- or communication-based approach—form instruction is incidental.",
    example:"During a discussion activity, the teacher briefly highlights a grammar point students consistently get wrong.",
    related:["t073","t067"] },
  { id:"t073", chapter:"ch6", term:"focus on forms", abbr:"",
    def:"An emphasis on formal aspects of language in isolation—the traditional approach of teaching grammar rules before using the language communicatively.",
    example:"Spending a whole class on the past perfect paradigm before any communicative practice.",
    related:["t072","t068"] },
  { id:"t074", chapter:"ch6", term:"input enhancement", abbr:"",
    def:"Various means of drawing attention to target language forms in the input—such as bolding, underlining, or increasing frequency—so that students will notice and learn them.",
    example:"Bolding all uses of the subjunctive in an authentic text is typographic input enhancement.",
    related:["t075","t054","t060"] },
  { id:"t075", chapter:"ch6", term:"input flooding", abbr:"",
    def:"Exposing learners to a text or materials that contain a substantially higher-than-natural frequency of a target linguistic feature, without explicitly drawing attention to it.",
    example:"Creating a reading passage that contains 30 instances of the passive voice for learners to process.",
    related:["t074","t072"] },
  { id:"t076", chapter:"ch6", term:"task-based language teaching", abbr:"TBLT",
    def:"An approach related to CLT that organizes instruction around communicative 'tasks'—real-world activities learners must complete using L2—making tasks the unit of language learning.",
    example:"Planning a class trip by reading brochures and negotiating choices in L2 is a TBLT task.",
    related:["t067","t072"] },
  { id:"t077", chapter:"ch6", term:"Processing Instruction", abbr:"PI",
    def:"VanPatten's pedagogical approach based on Input Processing theory; structured input activities push learners to process form-meaning connections rather than relying on meaning alone.",
    example:"Students hear 'The dog bit the cat' and 'The cat bit the dog' and indicate who bit whom—they must process word order.",
    related:["t051","t074"] },
  { id:"t078", chapter:"ch6", term:"corrective feedback", abbr:"CF",
    def:"Any pedagogical response to a learner's non-target-like utterance that provides information about the correct target form—including explicit correction, recasts, and prompts.",
    example:"Teacher: 'No, we say she went, not she goed. Repeat.' = explicit corrective feedback.",
    related:["t053","t062","t063"] },
  { id:"t079", chapter:"ch6", term:"uptake", abbr:"",
    def:"A learner's utterance that follows teacher feedback and incorporates—or attempts to incorporate—the correction provided.",
    example:"Teacher recasts 'She goed' → learner says 'Oh, she went'—that uptake shows the recast was noticed.",
    related:["t078","t062"] },
  { id:"t080", chapter:"ch6", term:"postmethod perspective", abbr:"",
    def:"The view (associated with Kumaravadivelu) that implementing any single method is misguided; effective teaching requires context-sensitive, principled decision-making beyond fixed methods.",
    example:"A teacher who adapts CLT principles to a Confucian-heritage classroom where public error is face-threatening is operating in postmethod perspective.",
    related:["t067","t072"] },
  { id:"t081", chapter:"ch6", term:"computer-assisted language learning", abbr:"CALL",
    def:"The use of computers and computerized resources in L2 learning, ranging from grammar drill software to AI-based conversation practice.",
    example:"Duolingo is a popular CALL application; more elaborate CALL tools include virtual reality immersion environments.",
    related:["t082"] },
  { id:"t082", chapter:"ch6", term:"computer-mediated communication", abbr:"CMC",
    def:"Communication accomplished through electronic devices—email, text messaging, video conferencing—which can provide L2 learners with authentic communicative contexts.",
    example:"Tandem language exchange via video call is an oral CMC activity.",
    related:["t081"] },
 
  // ─── CHAPTER 7 ───────────────────────────────────────────
  { id:"t083", chapter:"ch7", term:"cognates", abbr:"",
    def:"Words in related languages that developed from the same ancestral root and share a similar form and meaning (e.g., English 'table' and French 'table').",
    example:"English-Spanish cognates: 'hospital / hospital', 'natural / natural', 'president / presidente'.",
    related:["t084"] },
  { id:"t084", chapter:"ch7", term:"false cognates", abbr:"false friends",
    def:"Words in two languages that look or sound similar but have different meanings, often causing learner errors.",
    example:"Spanish 'embarazada' looks like 'embarrassed' but means 'pregnant'—a classic false friend.",
    related:["t083","t036"] },
  { id:"t085", chapter:"ch7", term:"developmental sequences", abbr:"",
    def:"Fixed, ordered series of stages in L2 acquisition (phonological, syntactic, semantic) that appear regardless of L1 background or instructional approach.",
    example:"English negation: first 'No go school' → then 'I no go' → then 'I don't go'—regardless of L1.",
    related:["t086","t033"] },
  { id:"t086", chapter:"ch7", term:"fossilization", abbr:"",
    def:"The cessation of development in certain aspects of the learner's interlanguage, leaving non-target-like structures or sounds permanently fixed despite continued exposure and motivation.",
    example:"A highly fluent L2 English speaker who permanently produces 'He don't know' may have fossilized this structure.",
    related:["t039","t085"] },
  { id:"t087", chapter:"ch7", term:"interlanguage pragmatics", abbr:"ILP",
    def:"The study of how L2 learners acquire and use pragmatic knowledge—understanding and producing speech acts (requests, apologies, refusals) appropriately in context.",
    example:"An L2 speaker who makes a blunt refusal when a more indirect one is culturally expected shows an ILP gap.",
    related:["t088","t039"] },
  { id:"t088", chapter:"ch7", term:"pragmatics", abbr:"",
    def:"The study of how context and situation affect the meaning of language—going beyond literal meaning to how we use language to accomplish social actions.",
    example:"'Can you pass the salt?' is pragmatically a request, not a question about ability.",
    related:["t087"] },
  { id:"t089", chapter:"ch7", term:"language corpora", abbr:"",
    def:"Large sets of usually computerized language data (millions of words of authentic speech or text) used to identify frequencies, patterns, and collocations.",
    example:"The British National Corpus and COCA are used to identify which preposition collocates with which verb.",
    related:["t003"] },
  { id:"t090", chapter:"ch7", term:"markedness", abbr:"",
    def:"The notion that certain linguistic features are more natural, frequent, and basic (unmarked) across languages, while others are more rare and complex (marked).",
    example:"The CVC syllable is unmarked; CCVCC (e.g., 'sprint') is marked—and harder for L2 learners.",
    related:["t091"] },
  { id:"t091", chapter:"ch7", term:"Markedness Differential Hypothesis", abbr:"MDH",
    def:"Eckman's (1977) hypothesis that L2 difficulty is determined by both L1-L2 difference (like CAH) and the relative markedness of structures—marked structures in L2 will be harder than unmarked ones.",
    example:"English codas (final consonants) are more marked than Spanish lacks them—thus harder for Spanish speakers.",
    related:["t090","t035"] },
  { id:"t092", chapter:"ch7", term:"Multidimensional Model", abbr:"",
    def:"Meisel, Clahsen & Pienemann's model distinguishing developmental features (acquired in fixed order due to processing constraints) from variational features (showing individual differences).",
    example:"German word order features are acquired in a fixed sequence regardless of L1 (developmental), while verb forms vary (variational).",
    related:["t093","t094"] },
  { id:"t093", chapter:"ch7", term:"Processability Theory", abbr:"PT",
    def:"Pienemann's theory that L2 developmental sequences are determined by the processing procedures learners can execute at each stage—you can only produce structures your processor can currently handle.",
    example:"Learners can't produce subject-verb inversion in questions before they've mastered phrasal agreement.",
    related:["t092","t094"] },
  { id:"t094", chapter:"ch7", term:"Teachability Hypothesis", abbr:"",
    def:"Pienemann's hypothesis (from PT) that instruction can only be effective when it targets a structure the learner is developmentally ready to acquire—teaching across stages is futile.",
    example:"Teaching inversion to a stage-2 learner is wasted; they must reach stage-3 readiness first.",
    related:["t092","t093"] },
  { id:"t095", chapter:"ch7", term:"Speech Learning Model", abbr:"SLM",
    def:"Flege's model predicting that L2 sounds similar to L1 sounds will be harder to learn (assimilated to existing categories) than sounds entirely new to the learner.",
    example:"Japanese learners assimilate English /l/ and /r/ to one L1 category, making both hard to distinguish.",
    related:["t085","t090"] },
 
  // ─── CHAPTER 8 ───────────────────────────────────────────
  { id:"t096", chapter:"ch8", term:"critical period", abbr:"",
    def:"A biologically determined period of time during which certain behaviors or skills (like language) are acquired with particular speed, ease, and completeness without formal instruction.",
    example:"Kittens deprived of visual stimulation during the critical period never develop normal vision—a biological analogy for language.",
    related:["t097","t098","t099"] },
  { id:"t097", chapter:"ch8", term:"Critical Period Hypothesis", abbr:"CPH",
    def:"The hypothesis (associated with Lenneberg, 1967) that there is a critical period—ending around puberty—for native-speaker-like L2 acquisition; after which full attainment is impossible.",
    example:"Studies show that immigrants who arrive before age 7 tend to attain native-like accents; those arriving after puberty rarely do.",
    related:["t096","t098","t100","t101"] },
  { id:"t098", chapter:"ch8", term:"sensitive period", abbr:"",
    def:"A weaker, more gradual version of the critical period—a window of heightened readiness for language acquisition without a sharp biological cut-off point.",
    example:"Some researchers prefer 'sensitive period' because age effects on L2 are gradient, not all-or-nothing.",
    related:["t097","t096"] },
  { id:"t099", chapter:"ch8", term:"lateralization", abbr:"",
    def:"The process by which cognitive functions, including language, become localized to one hemisphere of the brain (predominantly the left hemisphere in most people).",
    example:"Split-brain research and aphasia studies confirm that language is largely lateralized to the left hemisphere.",
    related:["t096","t097"] },
  { id:"t100", chapter:"ch8", term:"age of arrival", abbr:"AoA / AO",
    def:"The age at which an L2 learner first arrives in and is substantially exposed to the target language environment; a key variable in CPH research.",
    example:"Research consistently shows AoA is a strong predictor of ultimate attainment in L2 phonology.",
    related:["t097","t101"] },
  { id:"t101", chapter:"ch8", term:"length of residence", abbr:"LOR",
    def:"How long an L2 learner has lived in the target language community—a control variable used alongside AoA to separate exposure effects from age effects.",
    example:"Two learners with the same AoA but different LOR help isolate the effect of continued exposure.",
    related:["t100","t097"] },
  { id:"t102", chapter:"ch8", term:"feral child", abbr:"",
    def:"Term given to rare cases of children (like Genie) who grew up deprived of normal human interaction and language exposure—extreme test cases for the CPH.",
    example:"Genie, isolated until age 13, never fully acquired syntax, providing tragic support for a critical period.",
    related:["t096","t097"] },
  { id:"t103", chapter:"ch8", term:"imprinting", abbr:"",
    def:"Rapid, irreversible learning that occurs in young animals during a critical period when they pattern behavior on an adult model—used as a biological analogy for language acquisition.",
    example:"Konrad Lorenz's geese imprinted on him rather than their mother—a critical-period analogy.",
    related:["t096"] },
 
  // ─── CHAPTER 9 ───────────────────────────────────────────
  { id:"t104", chapter:"ch9", term:"aptitude", abbr:"",
    def:"A set of basic cognitive abilities that facilitate L2 learning and vary across individuals: phonetic coding ability, grammatical sensitivity, inductive ability, and rote learning ability.",
    example:"Students with high aptitude often learn grammar rules faster and retain vocabulary longer.",
    related:["t105","t106"] },
  { id:"t105", chapter:"ch9", term:"Modern Language Aptitude Test", abbr:"MLAT",
    def:"Carroll & Sapon's (1959) aptitude battery measuring four components—phonetic coding, grammatical sensitivity, rote memory, and inductive language learning ability.",
    example:"The MLAT was used to identify candidates most likely to succeed in intensive language training programs.",
    related:["t104","t106"] },
  { id:"t106", chapter:"ch9", term:"Attitude/Motivation Test Battery", abbr:"AMTB",
    def:"Gardner's widely used test battery measuring integrative motivation, attitude toward the learning situation, and language anxiety in L2 learners.",
    example:"The AMTB has been used in over 60 countries to study the relationship between motivation and L2 success.",
    related:["t104","t110"] },
  { id:"t107", chapter:"ch9", term:"basic interpersonal communicative skills", abbr:"BICS",
    def:"Cummins' term for the language skills needed for face-to-face personal communication—contextually embedded, cognitively undemanding language.",
    example:"Chatting on the playground or talking with friends uses BICS-level language.",
    related:["t108"] },
  { id:"t108", chapter:"ch9", term:"cognitive/academic language proficiency", abbr:"CALP",
    def:"Cummins' term for the language skills needed for academic tasks—abstract, cognitively demanding language largely decontextualized from immediate situations.",
    example:"Writing a literary analysis essay or solving a math word problem requires CALP.",
    related:["t107"] },
  { id:"t109", chapter:"ch9", term:"cognitive style", abbr:"",
    def:"An individual's habitual and preferred way of processing information—a relatively stable trait distinct from intelligence or learning strategies.",
    example:"A field-independent learner approaches a grammar problem by breaking it into parts; a field-dependent learner may struggle without the whole context.",
    related:["t114","t115"] },
  { id:"t110", chapter:"ch9", term:"extrinsic motivation", abbr:"",
    def:"Motivation driven by external rewards or pressures—grades, job requirements, parental expectations—rather than by inherent interest in the activity itself.",
    example:"Studying French only because it's required for graduation is extrinsic motivation.",
    related:["t111","t112","t113"] },
  { id:"t111", chapter:"ch9", term:"intrinsic motivation", abbr:"",
    def:"Motivation that comes from internal rewards—genuine interest, enjoyment, curiosity—rather than external incentives.",
    example:"Learning Japanese because you love anime and want to understand it is intrinsic motivation.",
    related:["t110","t112"] },
  { id:"t112", chapter:"ch9", term:"integrative orientation", abbr:"",
    def:"A desire to learn the L2 in order to identify with, join, or know more about the target language community and culture.",
    example:"An American learning Arabic because they want to connect with Arab culture and people is integratively oriented.",
    related:["t113","t111","t110"] },
  { id:"t113", chapter:"ch9", term:"instrumental orientation", abbr:"",
    def:"Motivation to learn an L2 primarily for practical purposes—career advancement, passing an exam, travel.",
    example:"A student learning English primarily to pass the TOEFL and study abroad is instrumentally oriented.",
    related:["t112","t110"] },
  { id:"t114", chapter:"ch9", term:"field dependence", abbr:"FD",
    def:"A cognitive style in which individuals tend to perceive the visual field as a whole (global/holistic perception) and have difficulty isolating parts from their embedding context.",
    example:"Field-dependent learners may excel at communicative tasks but struggle with isolated grammar exercises.",
    related:["t115","t109"] },
  { id:"t115", chapter:"ch9", term:"field independence", abbr:"FI",
    def:"A cognitive style in which individuals can readily identify parts of a visual field distinct from their background—analytical, part-focused perception.",
    example:"Field-independent learners may notice grammar patterns in input more readily.",
    related:["t114","t109"] },
  { id:"t116", chapter:"ch9", term:"learning strategies", abbr:"",
    def:"Specific, often conscious, actions, behaviors, and techniques that learners use to improve their L2 learning—cognitive, metacognitive, social, and affective strategies.",
    example:"Making vocabulary flashcards (cognitive), planning study sessions (metacognitive), and asking a native speaker for feedback (social) are all learning strategies.",
    related:["t117","t109"] },
  { id:"t117", chapter:"ch9", term:"learning style", abbr:"",
    def:"A person's usual and preferred way of acquiring, processing, and retaining new information—e.g., visual, auditory, kinesthetic, analytic, or global.",
    example:"A visual learner may prefer grammar presented in diagrams; an auditory learner benefits from listening.",
    related:["t116","t109"] },
  { id:"t118", chapter:"ch9", term:"motivation", abbr:"",
    def:"Gardner's (1985) construct: the combination of effort invested in learning + desire to achieve the goal + positive attitudes toward learning the L2.",
    example:"High motivation predicts long-term L2 achievement better than aptitude does in many studies.",
    related:["t110","t111","t112","t113","t106"] },
  { id:"t119", chapter:"ch9", term:"orientation", abbr:"",
    def:"The overall aim, purpose, direction, or goal of language learning—distinct from motivation (which is the driving force).",
    example:"Two students may both have high motivation but different orientations: one integrative, one instrumental.",
    related:["t112","t113","t118"] },
  { id:"t120", chapter:"ch9", term:"phonological short-term memory", abbr:"PSTM",
    def:"A subsystem of working memory responsible for the temporary storage of acoustic or speech-based information—strongly related to L2 vocabulary learning.",
    example:"People with high PSTM span can repeat longer nonwords and tend to acquire new vocabulary faster.",
    related:["t121","t104"] },
  { id:"t121", chapter:"ch9", term:"working memory", abbr:"WM",
    def:"An active, limited-capacity system for simultaneously storing and manipulating information during complex cognitive tasks such as L2 reading comprehension and sentence processing.",
    example:"WM capacity correlates with L2 listening comprehension—keeping earlier words active while processing later words.",
    related:["t120","t046","t065"] },
  { id:"t122", chapter:"ch9", term:"intelligence", abbr:"",
    def:"A hypothesized general cognitive factor underlying the ability to adapt to the environment, often measured by IQ tests—less predictive of L2 success in communicative contexts than in traditional ones.",
    example:"High IQ correlates more with formal grammar test scores than with oral communicative ability.",
    related:["t104","t121"] },
 
  // ─── CHAPTER 10 ───────────────────────────────────────────
  { id:"t123", chapter:"ch10", term:"bilingual first language acquisition", abbr:"BFLA",
    def:"The simultaneous acquisition of two languages from birth or very shortly thereafter, as occurs in children raised in bilingual households.",
    example:"A child born to a French-speaking mother and English-speaking father acquiring both simultaneously undergoes BFLA.",
    related:["t124","t127"] },
  { id:"t124", chapter:"ch10", term:"bilingual", abbr:"",
    def:"Someone who is able to use two languages—a broad term covering a wide range of proficiency levels from minimal to native-like in both languages.",
    example:"A person who can hold conversations and read in both Mandarin and English is bilingual.",
    related:["t123","t129"] },
  { id:"t125", chapter:"ch10", term:"bilingual lexical representation", abbr:"",
    def:"The way in which words from two languages are mentally stored and organized—whether in one shared conceptual store or two linked but separate lexical stores.",
    example:"The Bilingual Interactive Activation model proposes that both language lexicons are always active.",
    related:["t126","t130"] },
  { id:"t126", chapter:"ch10", term:"lexical access", abbr:"",
    def:"The process by which words are retrieved from the mental lexicon during language comprehension and production.",
    example:"In bilinguals, both languages compete for activation during lexical access, even in a monolingual context.",
    related:["t125","t130"] },
  { id:"t127", chapter:"ch10", term:"code-switching", abbr:"CS",
    def:"The practice of alternating between two languages or language varieties within a conversation or even a single utterance—a systematic, rule-governed behavior in bilingual communities.",
    example:"'I'm going to la tienda, ¿quieres algo?' mixes English and Spanish (common in US Latino communities).",
    related:["t128","t124"] },
  { id:"t128", chapter:"ch10", term:"mixed utterances", abbr:"",
    def:"Use of words or morphemes from both languages within a single utterance—common and normal in young bilingual children and distinct from pathological language mixing.",
    example:"A bilingual toddler saying 'More leche, please' (mixing English and Spanish) is producing mixed utterances.",
    related:["t127","t123"] },
  { id:"t129", chapter:"ch10", term:"executive control", abbr:"",
    def:"Higher-level cognitive processes localized in the frontal lobe—including attentional control, inhibition, and task-switching—that allow one to manage competing information.",
    example:"Bilinguals must use executive control to suppress the non-target language; research suggests this trains the executive system.",
    related:["t124","t130"] },
  { id:"t130", chapter:"ch10", term:"semantic priming", abbr:"",
    def:"A psycholinguistic phenomenon in which exposure to a semantically related word (prime) facilitates recognition of a target word—used to study bilingual lexical organization.",
    example:"'Nurse' primes 'doctor'—people respond faster to 'doctor' after seeing 'nurse' due to shared semantic network.",
    related:["t125","t126"] },
  { id:"t131", chapter:"ch10", term:"Stroop experiment", abbr:"",
    def:"A classic cognitive task showing color words in congruent or incongruent ink colors; participants must name the ink color—interference occurs when word meaning and ink color conflict.",
    example:"The word RED printed in blue ink causes interference—participants name the ink color slower.",
    related:["t129","t130"] },
  { id:"t132", chapter:"ch10", term:"language presentation", abbr:"",
    def:"The way languages are distributed in bilingual child-rearing—the most common strategy being one parent, one language (OPOL).",
    example:"A Japanese mother always speaks Japanese, while the American father always speaks English—OPOL.",
    related:["t123","t124"] },
  { id:"t133", chapter:"ch10", term:"cognitive reserve", abbr:"",
    def:"The brain's increased resilience against cognitive decline, hypothesized to result from lifelong bilingualism—bilinguals may show delayed onset of dementia symptoms.",
    example:"Bialystok et al. (2007) found that bilingual Alzheimer's patients showed symptom onset 4 years later than monolinguals.",
    related:["t129","t124"] },
];
 
// Convenience lookup
const TERM_MAP = Object.fromEntries(TERMS.map(t => [t.id, t]));
const CHAPTER_MAP = Object.fromEntries(CHAPTERS.map(c => [c.id, c]));
 
// Get terms by chapter
function getTermsByChapter(chapterId) {
  if (chapterId === 'all') return TERMS;
  return TERMS.filter(t => t.chapter === chapterId);
}
 
// Shuffle utility
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
 
// Fisher-Yates with seed — for reproducibility in some modes
function seededShuffle(arr, seed) {
  const a = [...arr];
  let s = seed;
  const rand = () => { s = (s * 9301 + 49297) % 233280; return s / 233280; };
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
 
